version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: mealie-postgres
    restart: always
    environment:
      POSTGRES_USER: mealie
      POSTGRES_PASSWORD: mealie_password
      POSTGRES_DB: mealie
    volumes:
      - mealie-db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  mealie:
    image: ghcr.io/mealie-recipes/mealie:latest
    container_name: mealie-frontend
    restart: always
    ports:
      - "9000:9000"
    environment:
      - DB_ENGINE=postgres
      - POSTGRES_USER=mealie
      - POSTGRES_PASSWORD=mealie_password
      - POSTGRES_SERVER=mealie-postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=mealie
      - POSTGRES_URL=postgresql://mealie:mealie_password@mealie-postgres:5432/mealie
      - ALLOW_SIGNUP=true
    depends_on:
      - postgres
    volumes:
      - mealie-app-data:/app/data/

  data-pipeline:
    build: .
    image: mealie-data
    container_name: data-pipeline-orchestrator
    depends_on:
      postgres:
        condition: service_started
      mealie:
        condition: service_started
    env_file:
      - .env
    command: ["bash", "orchestrator.sh"]
    volumes:
      - ./local_data:/app/local_data

volumes:
  mealie-db-data:
  mealie-app-data:
